{{- if not .Values.existingConfig.name  -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-mongodb-query-exporter.configName" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-mongodb-query-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-mongodb-query-exporter.chart" . }}
data:
  config.yaml: |
    {{- .Values.config | nindent 4 }}
{{- end -}}
